### ISSUE TITLE
Watermark `options` property has wrong type associated with it

### ISSUE THREAD

**Issue by uneos-papr** [watermarkify/vue-watermark#66]
Hi @wingkwong,

Thank you for creating this useful package! We noted a small issue:

While `options` is [defined as a nullary function returning a `WatermarkOptions` object](https://github.com/watermarkify/vue-watermark/blob/4c24349f010c23c5b3586b2ef99387051f07d686/src/components/Watermark.ts#L10-L11), the passed object for this property is never called but rather [deconstructed](https://github.com/watermarkify/vue-watermark/blob/4c24349f010c23c5b3586b2ef99387051f07d686/src/components/Watermark.ts#L25) (like one would do with an object).

Therefore, it looks like the type annotation is either incorrect or the passed object should be called.

Proposed fixes

1. Change the type annotation (backward compatible change)
```diff
   props: {
     options: {
-      type: Object as () => WatermarkOptions,
-      default: () => ({}),
+      type: Object as WatermarkOptions,
+      default: {},
     },
   },
```

2. Call the passed object (not backwards compatible)
```diff
     const options = reactive({
-      ...defaultOptions,
+      ...defaultOptions(),
       ...props.options,
       font: {
         ...defaultOptions.font,
-         ...props.options?.font,
+         ...props.options?().font,
       },
     })
```

Thank you for considering this issue and the proposed solutions. Let us know if using a function was actually intended and if we were overlooking anything in this regard.

Best,
Pablo

**Comment by wingkwong** [comment]
Hi Pablo,

What about just 

```diff
   props: {
     options: {
-      type: Object as () => WatermarkOptions,
-      default: () => ({}),
+      type: Object as PropType<WatermarkOptions>,
+      default: {},
     },
   },
```

Free feel to ping me at [Discord](https://discordapp.com/users/495466997304262658) for discussion.

**Comment by uneos-papr** [comment]
True, I forgot about the required `PropType<>`! I would be very happy with that solution!

**Comment by wingkwong** [comment]
@uneos-papr Can you help make a PR for that?
