### ISSUE TITLE
Warning: toRefs() expects a reactive object but received a plain one

### ISSUE THREAD

**Issue by uneos-papr** [watermarkify/vue-watermark#69]
Hi @wingkwong,

When using the `Watermark` component, I get the following warning

> [!WARNING]
> toRefs() expects a reactive object but received a plain one

I created a reproducible example here: https://playcode.io/1760402

I am not 100% sure, but my best guess is that it is caused by one of these two lines:

https://github.com/watermarkify/vue-watermark/blob/93d770df9012222c74a7ef15d726208f15c1a82f/src/components/Watermark.ts#L41-L42

Another thought: I wonder if it would make more sense to use [Vue's `computed()`](https://vuejs.org/guide/essentials/computed.html#computed-caching-vs-methods) functionality instead of `toRefs()`.

**Comment by wingkwong** [comment]
Thanks for reporting. I can reproduce in playground also. Will take a look.
